### ISSUE TITLE
Compiler crash during loop unroll 

### ISSUE THREAD

**Issue by bnikolic** [swift-lang/swift-t#98]
Following code

    int a[][];
    foreach i in [1:500]
    {
       foreach j in [1:500]
       {
         a[i][j]=3;
        }
      }
      
      int b[][];
      foreach x,i in a
      {
        foreach y,j in x
        {
          b[j][i]=a[i][j];
        }
      }

 will crash the compiler with -O3 : 

    ERROR STC internal error: please report this
    java.lang.ArithmeticException: / by zero
    	at exm.stc.ic.tree.ForeachLoops$RangeLoop.tryUnroll(ForeachLoops.java:811)
    	at exm.stc.ic.opt.LoopUnroller.unrollLoops(LoopUnroller.java:66)
    	at exm.stc.ic.opt.LoopUnroller.optimize(LoopUnroller.java:45)
    	at exm.stc.ic.opt.OptimizerPipeline.runPipeline(OptimizerPipeline.java:52)
    	at exm.stc.ic.opt.ICOptimizer.iterate(ICOptimizer.java:204)
    	at exm.stc.ic.opt.ICOptimizer.optimize(ICOptimizer.java:57)
    	at exm.stc.ic.STCMiddleEnd.optimize(STCMiddleEnd.java:130)
    	at exm.stc.ui.STCompiler.compileOnce(STCompiler.java:116)
    	at exm.stc.ui.STCompiler.compile(STCompiler.java:71)
            at exm.stc.ui.Main.main(Main.java:103)

works OK without -O3 or if foreach with element,index is replaced by a foreach across indices only. 

Found on exm-0.8.0

**Comment by jmjwozniak** [comment]
Thanks for reporting- apparently works now.  Thanks, Tim, for the quick fix!

**Comment by timarmstrong** [comment]
Was that the full program? The bug was that a previous optimisation pass left the loop body empty and the loop unroller didn't handle this case.

**Comment by bnikolic** [comment]
It's part of a larger program, which is a model (stub data, no computation) to test how dataflow approach fits our problem.  Thanks -- I can confirm the larger program compiles  too now.
